### PR TITLE
Fix the following issues

### LINKED ISSUE #30: When displaying English version, the file upload button is still in Japanese.
Normally, it depends on the browser's locale setting. But i18next might be able to fix it.

default

### LINKED ISSUE #34: Should not reload document after calling changeLanguage
Sakamoto-san is rewriting the language selection routine.

### PR DESCRIPTION
**Pull request by csKyou**
Closes #34 Should not reload document after calling changeLanguage
Closes #30 When displaying English version, the file upload button is still in Japanese.

### CODE REVIEW

File: appcell-resources/js/common.js [hunk 1]
```diff
@@ -481,14 +475,23 @@ cm.createBackMenu = function(moveUrl, flg) {
     cm.user.prevUrl = moveUrl;
 }
 
+// true: SettingTitle false: MainTitle
 cm.setTitleMenu = function(title, flg) {
     if (flg) {
-        $("#settingTitleMenu").html('<p class="ellipsisText">' + title + '</p>');
+        if (i18next.exists(title)) {
+            $("#settingTitleMenu").html('<p class="ellipsisText" data-i18n="' + title + '"></p>').localize();
```
Comment (dixonsiu) [inline appcell-resources/js/common.js]: Don't need to create the p tag every time.

File: appcell-resources/js/common.js [hunk 2]
```diff
@@ -785,6 +790,20 @@ cm.validateDescription = function(descriptionDetails, descriptionSpan) {
 	return isValidDescription;
 };
 
+cm.i18nAddProfile = function(lng , ns, boxName, json) {
```
Comment (dixonsiu) [inline appcell-resources/js/common.js]: For improvement, it might be better to use boxName as the namespace.
